version: v1

services:
  frontend:
    image: frontend:latest
    ports: 
      - 8080:8080
    environment: 
      BACKEND_DNS: localhost
      BACKEND_PORT: 9000
  backend:
    image: backend:latest