apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend_simple_fortune
spec:
  selector:
    app: backend_simple_fortune
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP