apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend_simple_fortune
  name: frontend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend_simple_fortune
  type: NodePort
