apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend_simple_fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend_simple_fortune
  template:
    metadata:
      labels:
        app: frontend_simple_fortune
    spec:
      containers:
      - name: frontend
        image: ghcr.io/mrodense/frontend_simple_fortune:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_PORT
          value: "9000"
        - name: BACKEND_DNS
          value: localhost