name: Build and Test
on:
  pull_request:
    branches: [ main ]
jobs:
  BuildAndTestGo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4   

      - name: Build frontend
        run: |
          cd frontend
          go build
      
      - name: Test fronend 
        run: |
          cd frontend
          go test

      - name: Build backend
        run: |
          cd backend
          go build
      
      - name: Test backend
        run: |
          cd backend
          go test
  

  BuildAndTestDocker: 
    runs-on: ubuntu-latest
    needs: [BuildAndTest]
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      
      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          dockerfile: Dockerfile
          tags: frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          dockerfile: Dockerfile
          tags: backend:latest
      
      - name: Deploy docker compose
        run: docker compose up -d

      - name: Test
        run: |
          sleep 20
          wget http://localhost:8080/
          test -f index.html
