name: Build and Test
on:
  push:
    branches:
      - "[0-9]*-**"
jobs: 
  BuildAndTestGo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4   

      - name: Build frontend
        run: |
          cd frontend
          go build
      
      - name: Test fronend 
        run: |
          cd frontend
          go test

      - name: Build backend
        run: |
          cd backend
          go build
      
      - name: Test backend
        run: |
          cd backend
          go test